name = "verifizierung-studie"
compatibility_date = "2024-06-01"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "chatdb", database_id = "ad1278f3-12cd-45ea-bd4e-abcdef123456" }

]
